<?php $item = $this->_getCollectionWidget($this->getAslideshowId()); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php if ($item) : ?>
<?php //foreach ($collection as $item) : ?><?php //echo '<pre>'; print_r($item->getProductList()); die('sdfsd'); ?>

<div class="slider">
    <div id="slider" class="flexslider">
	<!--if slideshow type is SLIDESHOW_IMAGE-->
	<?php
	    $_imageWidth = $item->getImageWidth();
	    $_imageHeight = $item->getImageHeight();
	?>
	<?php if($item->getSlideshowFor() == 'SLIDESHOW_IMAGE'): ?>
	
	    <?php $_imageList = $item->getImageList(); ?>
		<?php if (is_array($_imageList) and sizeof($_imageList) > 0) : ?>
		    <ul class="slides">
			<?php foreach ($_imageList as &$_item) : ?>
			    <li data-thumb="<?php echo $this->helper('aslideshow/image')->init($_item['file'])?>" style="width: <?php echo $_imageWidth?>; height: <?php echo $_imageHeight?>; <?php if($item->getTransition() == 'basic_carousel' || $item->getTransition() == 'carousel_min_max') : ?> margin: 0 <?php echo $item->getItemMargin() . 'px' ?><?php else : ?><?php endif; ?>">
				<?php if($_item['label'] == null) :?>
				    <img src="<?php echo $this->helper('aslideshow/image')->init($_item['file'])->resize($_imageWidth,$_imageHeight); ?>" alt="<?php echo $_item['caption']; ?>" />
				<?php else : ?>
				    <a href="<?php echo $_item['label']; ?>" title="" ><img src="<?php echo $this->helper('aslideshow/image')->init($_item['file'])->resize($_imageWidth,$_imageHeight); ?>" alt="<?php echo $_item['caption']; ?>" /></a>
				<?php endif; ?>
				<?php if($item->getShowText() == 1 && $_item['caption'] != null) :?>
				    <div style="opacity: <?php echo $item->getBackgroundOpacity(); ?>;" class="feature_excerpt"><?php echo $_item['caption']; ?></div>
				<?php endif; ?>
			    </li>
		        <?php endforeach; ?>
		    </ul>
		<?php endif; ?>
	
	<?php elseif($item->getSlideshowFor() == 'SLIDESHOW_PRODUCT'): ?>
	
	    <?php
		$_productImageWidth = $item->getProductImageWidth();
		$_productImageHeight = $item->getProductImageHeight();
	    ?>
	    <?php $_productIds = $item->getProductList(); ?>
	    <?php if (is_array($_productIds) and sizeof($_productIds) > 0) : ?>
		<ul class="slides">
		<?php foreach ($_productIds as &$_item) : ?>
		    <?php $_product = Mage::getModel('catalog/product')->load($_item['product_id']); ?>
		    <li data-thumb="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')?>" style="<?php if($item->getTransition() == 'basic_carousel' || $item->getTransition() == 'carousel_min_max') : ?> margin: 0 <?php echo $item->getItemMargin() . 'px' ?><?php else : ?><?php endif; ?>">
			<a href="<?php echo $_product->getProductUrl() ?>" title="" >
			    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_productImageWidth,$_productImageHeight); ?>"/>
			    <?php if($item->getShowText() == 1) :?>                   
				<div style="opacity: <?php echo $item->getBackgroundOpacity(); ?>;" class="feature_excerpt">
				    <div id="product-name" style="color: violet; font-family: Trebuchet MS; font-size: medium; font-weight: 500;">
					<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
				    </div>
				    <div id="product-detail" style="font-size: smaller"><i>
					<?php if($item->getShowPrice()): ?>
					    <?php echo $this->getPriceHtml($_product, true) ?>
					<?php endif; ?>
					<?php if($item->getShowDescription() == 'description'): ?>
					    Description: <?php echo $this->helper('core/string')->truncate($_helper->productAttribute($_product, $_product->getDescription(), 'description'), 100); ?>
					<?php elseif($item->getShowDescription() == 'short_description'): ?>
					    Short Description: <?php echo $this->helper('core/string')->truncate($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 100); ?>
					<?php else: ?>
					<?php endif; ?>
				    </i></div>
				</div>
			    <?php endif; ?>
			</a>
		    </li>
		<?php endforeach; ?>
		</ul>
	    <?php endif; ?>
	
	<?php else: ?>
	
	    <?php $_staticblocks = $item->getStaticblockList(); ?>
		<?php if (is_array($_staticblocks) and sizeof($_staticblocks) > 0) : ?>
		    <?php
			$staticImageWidth = $item->getStaticblockImageWidth();
			$staticImageHeight =  $item->getStaticblockImageHeight();
		    ?>
		    <ul class="slides">
		    <?php foreach ($_staticblocks as &$_item) : ?>
			<li <?php if($item->getTransition() == 'basic_carousel' || $item->getTransition() == 'carousel_min_max') : ?> margin: 0 <?php echo $item->getItemMargin() . 'px' ?><?php else : ?><?php endif; ?>>
			    <a href="#" title="">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($_item['staticblock_identifier'])->toHtml(); ?>
			    </a>
			</li>
		    <?php endforeach; ?>
		    </ul>
		<?php endif; ?>
		
	<?php endif; ?>
    </div>
    
    <?php if($item->getTransition() == 'thumbnail_slider') : ?>
	<div id="carousel" class="flexslider">
	    <?php
		$_imageWidth = $item->getImageWidth();
		$_imageHeight = $item->getImageHeight();
	    ?>
	    <?php if($item->getSlideshowFor() == 'SLIDESHOW_IMAGE'): ?>
		<?php $_imageList = $item->getImageList(); ?>
		<?php if (is_array($_imageList) and sizeof($_imageList) > 0) : ?>
		    <ul class="slides">
			<?php foreach ($_imageList as &$_item) : ?>
			    <li style="margin: 0 <?php echo $item->getItemMargin() . 'px' ?>">
				<img src="<?php echo $this->helper('aslideshow/image')->init($_item['file'])->resize($_imageWidth,$_imageHeight); ?>" alt="<?php echo $_item['caption']; ?>" />
			    </li>
			<?php endforeach; ?>
		    </ul>
		<?php endif; ?>
		
	    <!--if slideshow type is SLIDESHOW_PRODUCT-->
	    <?php elseif($item->getSlideshowFor() == 'SLIDESHOW_PRODUCT'): ?>
		<?php
		    $_productImageWidth = $item->getProductImageWidth();
		    $_productImageHeight = $item->getProductImageHeight();
		?>
		<?php $_productIds = $item->getProductList(); ?>
		<?php if (is_array($_productIds) and sizeof($_productIds) > 0) : ?>
		    <ul class="slides">
			<?php foreach ($_productIds as &$_item) : ?>
			    <?php $_product = Mage::getModel('catalog/product')->load($_item['product_id']); ?>
			    <li style="margin: 0 <?php echo $item->getItemMargin() . 'px' ?>">
				<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_productImageWidth,$_productImageHeight); ?>"/>
			    </li>
			<?php endforeach; ?>
		    </ul>
		<?php endif; ?>
	    
	    <!--if slideshow type is SLIDESHOW_STATIC_BLOCK-->
	    <?php else : ?>
		<?php $_staticblocks = $item->getStaticblockList(); ?>
		    <?php if (is_array($_staticblocks) and sizeof($_staticblocks) > 0) : ?>
			<?php
			    $staticImageWidth = $item->getStaticblockImageWidth();
			    $staticImageHeight =  $item->getStaticblockImageHeight();
			?>
			<ul class="slides">
			    <?php foreach ($_staticblocks as &$_item) : ?>
				<li style="margin: 0 <?php echo $item->getItemMargin() . 'px' ?>">
				    <a href="#" title="">
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($_item['staticblock_identifier'])->toHtml(); ?>
				    </a>
				</li>
			    <?php endforeach; ?>
			</ul>
			<?php endif; ?>
	    <?php endif; ?>
	</div>
    <?php endif; ?>
    
<script type="text/javascript">
    jQuery(window).load(function(){
	<?php if($item->getTransition() == 'thumbnail_slider') : ?>
	    jQuery('#carousel').flexslider({
		animation: 	"slide",
		controlNav: 	false,
		animationLoop: 	false,
		slideshow: 	<?php echo $item->getSlideshow() ?>,
		itemWidth: 	<?php echo $item->getItemWidth() ?>,
		itemMargin: 	<?php echo $item->getItemMargin() ?>,
		asNavFor: 	'#slider'
	    });
	    
	    jQuery('#slider').flexslider({
		animation: 	'<?php echo $item->getAnimation() ?>',
		controlNav: 	false,
		animationLoop: 	<?php echo $item->getAnimationLoop() ?>,
		direction:	'<?php echo $item->getDirection() ?>',
		smoothHeight:	<?php echo $item->getSmoothHeight() ?>,
		startAt: 	<?php echo $item->getStartAt() ?>,
		slideshowSpeed: <?php echo $item->getSlideshowSpeed(); ?>,
		animationSpeed: <?php echo $item->getAnimationSpeed() ?>,
		initDelay:	<?php echo $item->getInitDelay() ?>,
		randomize:	false,
		sync: 		"#carousel",
		start: function(slider){
		jQuery('body').removeClass('loading');
		}
	    });
	<?php else : ?>
	
	    jQuery('.flexslider').flexslider({
		
		<?php if($item->getTransition() == 'index') : ?>
		    animation: 		'<?php echo $item->getAnimation() ?>',
		    controlNav:		<?php echo $item->getControlNav()?>,
		<?php elseif($item->getTransition() == 'basic_carousel') : ?>
		    animation: 		'slide',
		    animationLoop: 	<?php echo $item->getAnimationLoop() ?>,
		    itemWidth:		<?php echo $item->getItemWidth() ?>,
		    itemMargin:		<?php echo $item->getItemMargin() ?>,
		    controlNav:		<?php echo $item->getControlNav()?>,
		<?php elseif($item->getTransition() == 'carousel_min_max') : ?>
		    animation: 		'slide',
		    animationLoop: 	<?php echo $item->getAnimationLoop() ?>,
		    itemWidth:		<?php echo $item->getItemWidth() ?>,
		    itemMargin:		<?php echo $item->getItemMargin() ?>,
		    minItems:		<?php echo $item->getMinItems() ?>,
		    maxItems:		<?php echo $item->getMaxItems() ?>,
		    controlNav:		<?php echo $item->getControlNav()?>,
		<?php elseif($item->getTransition() == 'thumbnail_controlnav') : ?>
		    animation: 		'<?php echo $item->getAnimation() ?>',
		    controlNav:		'thumbnails',
		<?php elseif($item->getTransition() == 'video') : ?>
		    animation: 		'<?php echo $item->getAnimation() ?>',
		    useCss:		<?php echo $item->getUseCss() ?>,
		    animationLoop: 	<?php echo $item->getAnimationLoop() ?>,
		    smoothHeight:	<?php echo $item->getSmoothHeight() ?>,
		    controlNav:		<?php echo $item->getControlNav()?>,
		<?php else : ?>
		<?php endif; ?>
		    //FlexSlider: Default Settings
		    direction:		'<?php echo $item->getDirection() ?>',
		    animationLoop: 	<?php echo $item->getAnimationLoop() ?>,
		    smoothHeight:	<?php echo $item->getSmoothHeight() ?>,
		    startAt: 		<?php echo $item->getStartAt() ?>,
		    slideshow: 		<?php echo $item->getSlideshow() ?>,
		    slideshowSpeed: 	<?php echo $item->getSlideshowSpeed(); ?>,
		    animationSpeed: 	<?php echo $item->getAnimationSpeed() ?>,
		    initDelay:		<?php echo $item->getInitDelay() ?>,
		    randomize:		<?php echo $item->getRandomize() ?>,
		    
		start: function(slider){
		jQuery('body').removeClass('loading');
	    }
	    });
	    <?php endif; ?>
    });
</script>
</div>

<div style="clear:both;"></div>
<!-- Copyright -->
<div style="position:absolute;top:-8888px;">Copyright &copy;2013&nbsp;<a href="http://www.magesolution.com/">Magesolution.com</a>&nbsp;|&nbsp;<a href="http://www.magesolution.com/magento-responsive-slideshow.html">Responsive Slideshow</a></div>
<?php endif; ?>
